PRAGMA defer_foreign_keys=TRUE;
BEGIN TRANSACTION;
INSERT INTO "bundle_discount_products" ("bundle_id","product_id") VALUES('bd1','n14');
INSERT INTO "bundle_discount_products" ("bundle_id","product_id") VALUES('bd1','n15');
INSERT INTO "bundle_discounts" ("id","name","discount_type","discount_value") VALUES('bd1','組合折扣','percent',10);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('name','姓名','text',1,1,0);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('phone','電話','tel',1,1,1);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('lineId','LINE ID（滿 3,000 元可加入會員專屬群組）','text',1,1,2);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('email','電子郵件','email',1,1,3);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('zip','郵遞區號','text',0,1,4);
INSERT INTO "customer_fields" ("id","label","type","required","builtin","sort_order") VALUES('address','地址','text',1,1,5);
INSERT INTO "product_images" ("id","product_id","url","sort_order") VALUES(1,'n1','/images/products/n1-0.jpg',0);
INSERT INTO "product_images" ("id","product_id","url","sort_order") VALUES(2,'n2','/images/products/n2-0.jpg',0);
INSERT INTO "product_images" ("id","product_id","url","sort_order") VALUES(3,'n3','/images/products/n3-0.jpg',0);
INSERT INTO "product_statuses" ("id","label","type","color") VALUES('ok','正常上架','purchasable',NULL);
INSERT INTO "product_statuses" ("id","label","type","color") VALUES('soldout','已售完 Sold Out','tag','#d97b63');
INSERT INTO "product_statuses" ("id","label","type","color") VALUES('comingsoon','棋願製造中','tag','#c9bfa8');
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n1',replace('2026春 八卦山山脊 武夷 種\n著蜒球形包種茶','\n',char(10)),'THE NEW',915,2265,3810,'SIGNATURE TEA','ok',0);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n2','2026春 名間鄉埔中村 翠玉 種 球形包種茶','THE NEW',595,1470,2470,'逐漸稀少','ok',1);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n3','2026春 竹山大沼澤 金萱 種 中火球形包種茶','THE NEW',920,2270,3810,NULL,'ok',2);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n4','2026春 桃園龍潭 金萱 種 條形包種茶','THE NEW',1170,2885,4840,NULL,'ok',3);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n5','2026春 杉林溪 紅心烏龍 種 球形包種茶','THE NEW',610,1505,2525,'特殊品種．重焙','ok',4);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n6','2026春 六龜深山 百年古樹山茶 種 東方美人茶','THE NEW',2980,7360,12360,'一年一產．極稀有品種','ok',5);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n7','2026春 拉拉山 青心烏龍 種 條形包種茶','THE NEW',1475,3640,6125,'最高海拔有機茶園','ok',6);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n8','2026春 坪林 大慢 種 條形包種茶','THE NEW',920,2270,3810,'古董級稀有品種','ok',7);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n9','2026春 帖比倫瀑布 青心烏龍 種 球形包種茶','THE NEW',795,1965,3295,NULL,'ok',8);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n10','2026春 杉林溪軟鞍 青心烏龍 種 球形包種茶','THE NEW',670,1655,2780,NULL,'ok',9);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n12','2026春 魚池大雁村 台茶十八號紅玉 種 英式紅茶','THE NEW',980,2420,4065,NULL,'ok',10);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n13','2026春 魚池大雁村 近百年古樹 種 英式紅茶','THE NEW',1165,2880,4840,'稀有品種','ok',11);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n14','2026春 玉山草坪頭 紅心歪尾桃 種 中火球形包種茶','THE NEW',1535,3800,6380,'鐵觀音','ok',12);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n15','2026春 玉山草坪頭 紅心歪尾桃 種 重火球形包種茶','THE NEW',1565,3870,6500,'鐵觀音','ok',13);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n16','2026春 白姑山山脊 青心烏龍 種 球形包種茶','THE NEW',1045,2575,4625,'風土特殊．台灣岩茶','ok',14);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n17','2026春 鹿野小台地 沁玉 種 球形包種茶','THE NEW',915,2260,3800,NULL,'ok',15);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n18','2026春 鹿野小台地 沁玉 種 中火球形包種茶','THE NEW',980,2450,4080,NULL,'ok',16);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('n19','2026春 鹿野小台地 沁玉 種 重火球形包種茶','THE NEW',1020,2520,4245,NULL,'ok',17);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c1','2025春 八卦山山脊 武夷 種 著蜒球形包種茶','THE CENTER',NULL,NULL,NULL,NULL,'soldout',18);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c2','2025春 玉山草坪頭 佛手 種 中火球形包種茶','THE CENTER',1405,3605,6075,NULL,'ok',19);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c3','2025春 凍頂永隆 青心烏龍&金萱 種 中火球形包種茶','THE CENTER',NULL,NULL,NULL,'少見混種茶園','soldout',20);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c4','2025冬 埔中小山丘 四季春 種 中火球形包種茶','THE CENTER',395,985,1650,NULL,'ok',21);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c5','2025冬 八卦山山脊 武夷 種 著蜒球形包種茶','THE CENTER',1105,2730,4585,'SIGNATURE TEA','ok',22);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c6','2025冬 小半天 沁玉&金萱&迎香 種 中火球形包種茶','THE CENTER',825,1825,3240,'少見混種茶園','ok',23);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c7','2025春 白姑山山脊 青心烏龍 種 重火球形包種茶','THE CENTER',NULL,NULL,NULL,NULL,'soldout',24);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c8','2025春 名間鄉埔中村 銀龍 種 番庄烏龍茶','THE CENTER',NULL,NULL,NULL,'當地特有茶樹種','soldout',25);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c9','2025春 埔里白魚保護區 迎香 種 著蜒番庄烏龍茶','THE CENTER',NULL,NULL,NULL,NULL,'soldout',26);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c10','2025夏 名間鄉松柏嶺 台茶14號半白鴿 種 東方美人茶','THE CENTER',1555,4065,6825,'當地特有茶樹種','ok',27);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c11','2025夏 名間鄉松柏嶺 台茶14號半白鴿 種 英式紅茶','THE CENTER',750,1660,2940,'當地特有茶樹種','ok',28);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('c12','2026春 玉山草坪頭 阿拉比卡分支 有機咖啡 淺中焙','THE CENTER',NULL,NULL,NULL,'一年一產','soldout',29);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('no1','2025夏 苗栗小山丘 黃心烏龍 種 條形包種茶','THE NORTH',1335,3300,5535,'罕見品種','ok',30);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('no2','2025夏 苗栗小山丘 黃心烏龍 種 東方美人茶','THE NORTH',1405,3605,6075,'罕見品種與全手路','ok',31);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('no3','2025秋 苗栗小山丘 黃心烏龍 種 黃茶','THE NORTH',1305,3220,5407,'罕見品種與特殊製程','ok',32);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('no4','2025秋 苗栗小山丘 黃心烏龍 種 東方美人茶','THE NORTH',1515,3760,6310,'罕見品種與全手路','ok',33);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('no5','2025夏 苗栗小山丘 青心大冇 種 英式紅茶','THE NORTH',1130,2505,4440,NULL,'ok',34);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('s1','2025春 六龜深山 百年原生山茶 種 東方美人茶','THE SOUTH',NULL,NULL,NULL,'極稀有品種','soldout',35);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('s2','2025冬 六龜花果山旁 蒔生山茶 種 東方美人茶','THE SOUTH',1665,3685,6540,NULL,'ok',36);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('s3','2025冬 港口村 港口武夷古 種 球形包種茶','THE SOUTH',1460,3180,6150,'售完即絕版','ok',37);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e1','2025春 鹿野小台地 武夷 種 著蜒球形包種茶','THE EAST',NULL,NULL,NULL,'SIGNATURE TEA','soldout',38);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e2','2025春 花蓮海岸山脈 佛手 種 中火球形包種茶','THE EAST',1455,3760,6325,NULL,'ok',39);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e3','2025春 鹿野小台地 大葉烏龍 種 著蜒球形包種茶','THE EAST',1205,2990,5075,'THE FAVORITE','ok',40);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e4','2025春 花蓮海岸山脈 蒔生山茶 種 番庄烏龍茶','THE EAST',1070,2580,4400,NULL,'ok',41);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e5','2025春 花蓮海岸山脈 蒔生山茶 種 東方美人茶','THE EAST',1220,3035,5150,NULL,'ok',42);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('e6','2025春 鹿野小鄉間 大葉烏龍 種 紅烏龍茶','THE EAST',NULL,NULL,NULL,'DELICIOUS','soldout',43);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f1','2025冬 鹿野小台地 沁玉2號 種 球形包種茶','風土と發酵',1015,2500,4200,'THE NEW TEA TREE','ok',44);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f2','2025冬 鹿野小台地 沁四4號 種 球形包種茶','風土と發酵',1045,2580,4325,NULL,'ok',45);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f3','2025冬 鹿野小台地 沁玉6號 種 球形包種茶','風土と發酵',1060,2625,4405,NULL,'ok',46);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f4','2026春 白姑山山脊 青心烏龍 種 球形包種茶','風土と發酵',1045,2575,4625,'風土特殊．台灣岩茶','ok',47);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f5','2026春 帖比倫瀑布 青心烏龍 種 球形包種茶','風土と發酵',795,1965,3295,NULL,'ok',48);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('f6','2026春 杉林溪軟鞍 青心烏龍 種 球形包種茶','風土と發酵',670,1655,2780,NULL,'ok',49);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z1','2026春 玉山草坪頭 紅心歪尾桃 種 中火球形包種茶','走水と炭焙',1535,3800,6380,NULL,'ok',50);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z2','2026春 玉山草坪頭 紅心歪尾桃 種 重火球形包種茶','走水と炭焙',1565,3870,6500,'鐵觀音','ok',51);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z5','2026春 凍頂永隆A 青心烏龍 種 球形包種茶','走水と炭焙',1045,2580,4325,'走水完美版','ok',52);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z6','2026春 凍頂永隆B 青心烏龍 種 球形包種茶','走水と炭焙',650,1655,2785,'走水稍卡版','ok',53);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z7','2025冬 竹山大沼澤 金萱 種 走乾球形包種茶','走水と炭焙',700,1555,2760,NULL,'ok',54);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z8','2025冬 竹山大沼澤 金萱 種 中火球形包種茶','走水と炭焙',725,1605,2850,NULL,'ok',55);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z9','2025冬 竹山大沼澤 金萱 種 重火球形包種茶','走水と炭焙',750,1660,2940,NULL,'ok',56);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z10','2025冬 帖比倫瀑布 青心烏龍 種 走乾球形包種茶','走水と炭焙',780,1725,3060,NULL,'ok',57);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z11','2025冬 帖比倫瀑布 青心烏龍 種 中火球形包種茶','走水と炭焙',800,1775,3150,NULL,'ok',58);
INSERT INTO "products" ("id","name","region_id","price_30","price_80","price_150","note","status_id","sort_order") VALUES('z12','2025冬 帖比倫瀑布 青心烏龍 種 重火球形包種茶','走水と炭焙',825,1825,3240,NULL,'ok',59);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('THE NEW','THE NEW','茶光島嶼と新風土',NULL,'center','/images/regions/the-new-desktop.jpg','/images/regions/the-new-desktop.jpg',0);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('THE CENTER','THE CENTER','中央山脈と石虎の森林氣息',NULL,'center 62%','/images/regions/the-center-desktop.jpg','/images/regions/the-center-desktop.jpg',1);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('THE NORTH','THE NORTH','丘陵 貓裏 恁仔細',NULL,'center 70%','/images/regions/the-north-desktop.jpg','/images/regions/the-north-desktop.jpg',2);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('THE SOUTH','THE SOUTH','烈日、紅土と頁岩的淬鍊',NULL,'center 50%','/images/regions/the-south-desktop.jpg','/images/regions/the-south-desktop.jpg',3);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('THE EAST','THE EAST','曙光與太平洋的呼吸',NULL,'center','/images/regions/the-east-desktop.jpg','/images/regions/the-east-desktop.jpg',4);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('風土と發酵','風土と發酵','の垂直饗宴','此系列三入一組享組合價','center','/images/regions/fengtu-fajiao-desktop.jpg','/images/regions/fengtu-fajiao-desktop.jpg',5);
INSERT INTO "regions" ("id","title","subtitle","note","bg_pos","bg_image","bg_image_mobile","sort_order") VALUES('走水と炭焙','走水と炭焙','の秘法','此系列三入一組享組合價','center','/images/regions/zoushui-tanbei-desktop.jpg','/images/regions/zoushui-tanbei-desktop.jpg',6);
INSERT INTO "site_settings" ("key","value") VALUES('theme.scaleTitle','1');
INSERT INTO "site_settings" ("key","value") VALUES('theme.scaleItem','1');
INSERT INTO "site_settings" ("key","value") VALUES('theme.scalePrice','1');
INSERT INTO "site_settings" ("key","value") VALUES('theme.colorTitle','#f3ede1');
INSERT INTO "site_settings" ("key","value") VALUES('theme.colorItem','#f3ede1');
INSERT INTO "site_settings" ("key","value") VALUES('theme.colorPrice','#c98a4b');
INSERT INTO "site_settings" ("key","value") VALUES('shipping.freeThreshold','3000');
INSERT INTO "site_settings" ("key","value") VALUES('shipping.fee','100');
INSERT INTO "site_settings" ("key","value") VALUES('notify.shopEmail','');
INSERT INTO "site_settings" ("key","value") VALUES('branding.logoImage','/images/logo.png');
INSERT INTO "site_settings" ("key","value") VALUES('branding.linePayQrImage','/images/line-pay-qr.png');
INSERT INTO "site_settings" ("key","value") VALUES('weightOptions','[30,80,150]');
COMMIT;
