import type { Region, Product, ProductStatus, CustomerField, BundleDiscount } from "./types";

export const REGIONS: Region[] = [
  {
    id: "THE NEW",
    title: "THE NEW",
    subtitle: "茶光島嶼と新風土",
    note: null,
    bgPos: "center",
    bgImage: "/images/regions/the-new-desktop.jpg",
    bgImageMobile: "/images/regions/the-new-desktop.jpg",
  },
  {
    id: "THE CENTER",
    title: "THE CENTER",
    subtitle: "中央山脈と石虎の森林氣息",
    note: null,
    bgPos: "center 62%",
    bgImage: "/images/regions/the-center-desktop.jpg",
    bgImageMobile: "/images/regions/the-center-desktop.jpg",
  },
  {
    id: "THE NORTH",
    title: "THE NORTH",
    subtitle: "丘陵 貓裏 恁仔細",
    note: null,
    bgPos: "center 70%",
    bgImage: "/images/regions/the-north-desktop.jpg",
    bgImageMobile: "/images/regions/the-north-desktop.jpg",
  },
  {
    id: "THE SOUTH",
    title: "THE SOUTH",
    subtitle: "烈日、紅土と頁岩的淬鍊",
    note: null,
    bgPos: "center 50%",
    bgImage: "/images/regions/the-south-desktop.jpg",
    bgImageMobile: "/images/regions/the-south-desktop.jpg",
  },
  {
    id: "THE EAST",
    title: "THE EAST",
    subtitle: "曙光與太平洋的呼吸",
    note: null,
    bgPos: "center",
    bgImage: "/images/regions/the-east-desktop.jpg",
    bgImageMobile: "/images/regions/the-east-desktop.jpg",
  },
  {
    id: "風土と發酵",
    title: "風土と發酵",
    subtitle: "の垂直饗宴",
    note: "此系列三入一組享組合價",
    bgPos: "center",
    bgImage: "/images/regions/fengtu-fajiao-desktop.jpg",
    bgImageMobile: "/images/regions/fengtu-fajiao-desktop.jpg",
  },
  {
    id: "走水と炭焙",
    title: "走水と炭焙",
    subtitle: "の秘法",
    note: "此系列三入一組享組合價",
    bgPos: "center",
    bgImage: "/images/regions/zoushui-tanbei-desktop.jpg",
    bgImageMobile: "/images/regions/zoushui-tanbei-desktop.jpg",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "n1",
    name: "2026春 八卦山山脊 武夷 種\n著蜒球形包種茶",
    region: "THE NEW",
    prices: { "30": 915, "80": 2265, "150": 3810 },
    note: "SIGNATURE TEA",
    statusId: "ok",
    images: ["/images/products/n1-0.jpg"],
  },
  {
    id: "n2",
    name: "2026春 名間鄉埔中村 翠玉 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 595, "80": 1470, "150": 2470 },
    note: "逐漸稀少",
    statusId: "ok",
    images: ["/images/products/n2-0.jpg"],
  },
  {
    id: "n3",
    name: "2026春 竹山大沼澤 金萱 種 中火球形包種茶",
    region: "THE NEW",
    prices: { "30": 920, "80": 2270, "150": 3810 },
    note: null,
    statusId: "ok",
    images: ["/images/products/n3-0.jpg"],
  },
  {
    id: "n4",
    name: "2026春 桃園龍潭 金萱 種 條形包種茶",
    region: "THE NEW",
    prices: { "30": 1170, "80": 2885, "150": 4840 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n5",
    name: "2026春 杉林溪 紅心烏龍 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 610, "80": 1505, "150": 2525 },
    note: "特殊品種．重焙",
    statusId: "ok",
    images: [],
  },
  {
    id: "n6",
    name: "2026春 六龜深山 百年古樹山茶 種 東方美人茶",
    region: "THE NEW",
    prices: { "30": 2980, "80": 7360, "150": 12360 },
    note: "一年一產．極稀有品種",
    statusId: "ok",
    images: [],
  },
  {
    id: "n7",
    name: "2026春 拉拉山 青心烏龍 種 條形包種茶",
    region: "THE NEW",
    prices: { "30": 1475, "80": 3640, "150": 6125 },
    note: "最高海拔有機茶園",
    statusId: "ok",
    images: [],
  },
  {
    id: "n8",
    name: "2026春 坪林 大慢 種 條形包種茶",
    region: "THE NEW",
    prices: { "30": 920, "80": 2270, "150": 3810 },
    note: "古董級稀有品種",
    statusId: "ok",
    images: [],
  },
  {
    id: "n9",
    name: "2026春 帖比倫瀑布 青心烏龍 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 795, "80": 1965, "150": 3295 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n10",
    name: "2026春 杉林溪軟鞍 青心烏龍 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 670, "80": 1655, "150": 2780 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n12",
    name: "2026春 魚池大雁村 台茶十八號紅玉 種 英式紅茶",
    region: "THE NEW",
    prices: { "30": 980, "80": 2420, "150": 4065 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n13",
    name: "2026春 魚池大雁村 近百年古樹 種 英式紅茶",
    region: "THE NEW",
    prices: { "30": 1165, "80": 2880, "150": 4840 },
    note: "稀有品種",
    statusId: "ok",
    images: [],
  },
  {
    id: "n14",
    name: "2026春 玉山草坪頭 紅心歪尾桃 種 中火球形包種茶",
    region: "THE NEW",
    prices: { "30": 1535, "80": 3800, "150": 6380 },
    note: "鐵觀音",
    statusId: "ok",
    images: [],
  },
  {
    id: "n15",
    name: "2026春 玉山草坪頭 紅心歪尾桃 種 重火球形包種茶",
    region: "THE NEW",
    prices: { "30": 1565, "80": 3870, "150": 6500 },
    note: "鐵觀音",
    statusId: "ok",
    images: [],
  },
  {
    id: "n16",
    name: "2026春 白姑山山脊 青心烏龍 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 1045, "80": 2575, "150": 4625 },
    note: "風土特殊．台灣岩茶",
    statusId: "ok",
    images: [],
  },
  {
    id: "n17",
    name: "2026春 鹿野小台地 沁玉 種 球形包種茶",
    region: "THE NEW",
    prices: { "30": 915, "80": 2260, "150": 3800 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n18",
    name: "2026春 鹿野小台地 沁玉 種 中火球形包種茶",
    region: "THE NEW",
    prices: { "30": 980, "80": 2450, "150": 4080 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "n19",
    name: "2026春 鹿野小台地 沁玉 種 重火球形包種茶",
    region: "THE NEW",
    prices: { "30": 1020, "80": 2520, "150": 4245 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "c1",
    name: "2025春 八卦山山脊 武夷 種 著蜒球形包種茶",
    region: "THE CENTER",
    prices: null,
    note: null,
    statusId: "soldout",
    images: [],
  },
  {
    id: "c2",
    name: "2025春 玉山草坪頭 佛手 種 中火球形包種茶",
    region: "THE CENTER",
    prices: { "30": 1405, "80": 3605, "150": 6075 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "c3",
    name: "2025春 凍頂永隆 青心烏龍&金萱 種 中火球形包種茶",
    region: "THE CENTER",
    prices: null,
    note: "少見混種茶園",
    statusId: "soldout",
    images: [],
  },
  {
    id: "c4",
    name: "2025冬 埔中小山丘 四季春 種 中火球形包種茶",
    region: "THE CENTER",
    prices: { "30": 395, "80": 985, "150": 1650 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "c5",
    name: "2025冬 八卦山山脊 武夷 種 著蜒球形包種茶",
    region: "THE CENTER",
    prices: { "30": 1105, "80": 2730, "150": 4585 },
    note: "SIGNATURE TEA",
    statusId: "ok",
    images: [],
  },
  {
    id: "c6",
    name: "2025冬 小半天 沁玉&金萱&迎香 種 中火球形包種茶",
    region: "THE CENTER",
    prices: { "30": 825, "80": 1825, "150": 3240 },
    note: "少見混種茶園",
    statusId: "ok",
    images: [],
  },
  {
    id: "c7",
    name: "2025春 白姑山山脊 青心烏龍 種 重火球形包種茶",
    region: "THE CENTER",
    prices: null,
    note: null,
    statusId: "soldout",
    images: [],
  },
  {
    id: "c8",
    name: "2025春 名間鄉埔中村 銀龍 種 番庄烏龍茶",
    region: "THE CENTER",
    prices: null,
    note: "當地特有茶樹種",
    statusId: "soldout",
    images: [],
  },
  {
    id: "c9",
    name: "2025春 埔里白魚保護區 迎香 種 著蜒番庄烏龍茶",
    region: "THE CENTER",
    prices: null,
    note: null,
    statusId: "soldout",
    images: [],
  },
  {
    id: "c10",
    name: "2025夏 名間鄉松柏嶺 台茶14號半白鴿 種 東方美人茶",
    region: "THE CENTER",
    prices: { "30": 1555, "80": 4065, "150": 6825 },
    note: "當地特有茶樹種",
    statusId: "ok",
    images: [],
  },
  {
    id: "c11",
    name: "2025夏 名間鄉松柏嶺 台茶14號半白鴿 種 英式紅茶",
    region: "THE CENTER",
    prices: { "30": 750, "80": 1660, "150": 2940 },
    note: "當地特有茶樹種",
    statusId: "ok",
    images: [],
  },
  {
    id: "c12",
    name: "2026春 玉山草坪頭 阿拉比卡分支 有機咖啡 淺中焙",
    region: "THE CENTER",
    prices: null,
    note: "一年一產",
    statusId: "soldout",
    images: [],
  },
  {
    id: "no1",
    name: "2025夏 苗栗小山丘 黃心烏龍 種 條形包種茶",
    region: "THE NORTH",
    prices: { "30": 1335, "80": 3300, "150": 5535 },
    note: "罕見品種",
    statusId: "ok",
    images: [],
  },
  {
    id: "no2",
    name: "2025夏 苗栗小山丘 黃心烏龍 種 東方美人茶",
    region: "THE NORTH",
    prices: { "30": 1405, "80": 3605, "150": 6075 },
    note: "罕見品種與全手路",
    statusId: "ok",
    images: [],
  },
  {
    id: "no3",
    name: "2025秋 苗栗小山丘 黃心烏龍 種 黃茶",
    region: "THE NORTH",
    prices: { "30": 1305, "80": 3220, "150": 5407 },
    note: "罕見品種與特殊製程",
    statusId: "ok",
    images: [],
  },
  {
    id: "no4",
    name: "2025秋 苗栗小山丘 黃心烏龍 種 東方美人茶",
    region: "THE NORTH",
    prices: { "30": 1515, "80": 3760, "150": 6310 },
    note: "罕見品種與全手路",
    statusId: "ok",
    images: [],
  },
  {
    id: "no5",
    name: "2025夏 苗栗小山丘 青心大冇 種 英式紅茶",
    region: "THE NORTH",
    prices: { "30": 1130, "80": 2505, "150": 4440 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "s1",
    name: "2025春 六龜深山 百年原生山茶 種 東方美人茶",
    region: "THE SOUTH",
    prices: null,
    note: "極稀有品種",
    statusId: "soldout",
    images: [],
  },
  {
    id: "s2",
    name: "2025冬 六龜花果山旁 蒔生山茶 種 東方美人茶",
    region: "THE SOUTH",
    prices: { "30": 1665, "80": 3685, "150": 6540 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "s3",
    name: "2025冬 港口村 港口武夷古 種 球形包種茶",
    region: "THE SOUTH",
    prices: { "30": 1460, "80": 3180, "150": 6150 },
    note: "售完即絕版",
    statusId: "ok",
    images: [],
  },
  {
    id: "e1",
    name: "2025春 鹿野小台地 武夷 種 著蜒球形包種茶",
    region: "THE EAST",
    prices: null,
    note: "SIGNATURE TEA",
    statusId: "soldout",
    images: [],
  },
  {
    id: "e2",
    name: "2025春 花蓮海岸山脈 佛手 種 中火球形包種茶",
    region: "THE EAST",
    prices: { "30": 1455, "80": 3760, "150": 6325 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "e3",
    name: "2025春 鹿野小台地 大葉烏龍 種 著蜒球形包種茶",
    region: "THE EAST",
    prices: { "30": 1205, "80": 2990, "150": 5075 },
    note: "THE FAVORITE",
    statusId: "ok",
    images: [],
  },
  {
    id: "e4",
    name: "2025春 花蓮海岸山脈 蒔生山茶 種 番庄烏龍茶",
    region: "THE EAST",
    prices: { "30": 1070, "80": 2580, "150": 4400 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "e5",
    name: "2025春 花蓮海岸山脈 蒔生山茶 種 東方美人茶",
    region: "THE EAST",
    prices: { "30": 1220, "80": 3035, "150": 5150 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "e6",
    name: "2025春 鹿野小鄉間 大葉烏龍 種 紅烏龍茶",
    region: "THE EAST",
    prices: null,
    note: "DELICIOUS",
    statusId: "soldout",
    images: [],
  },
  {
    id: "f1",
    name: "2025冬 鹿野小台地 沁玉2號 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 1015, "80": 2500, "150": 4200 },
    note: "THE NEW TEA TREE",
    statusId: "ok",
    images: [],
  },
  {
    id: "f2",
    name: "2025冬 鹿野小台地 沁四4號 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 1045, "80": 2580, "150": 4325 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "f3",
    name: "2025冬 鹿野小台地 沁玉6號 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 1060, "80": 2625, "150": 4405 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "f4",
    name: "2026春 白姑山山脊 青心烏龍 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 1045, "80": 2575, "150": 4625 },
    note: "風土特殊．台灣岩茶",
    statusId: "ok",
    images: [],
  },
  {
    id: "f5",
    name: "2026春 帖比倫瀑布 青心烏龍 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 795, "80": 1965, "150": 3295 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "f6",
    name: "2026春 杉林溪軟鞍 青心烏龍 種 球形包種茶",
    region: "風土と發酵",
    prices: { "30": 670, "80": 1655, "150": 2780 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z1",
    name: "2026春 玉山草坪頭 紅心歪尾桃 種 中火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 1535, "80": 3800, "150": 6380 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z2",
    name: "2026春 玉山草坪頭 紅心歪尾桃 種 重火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 1565, "80": 3870, "150": 6500 },
    note: "鐵觀音",
    statusId: "ok",
    images: [],
  },
  {
    id: "z5",
    name: "2026春 凍頂永隆A 青心烏龍 種 球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 1045, "80": 2580, "150": 4325 },
    note: "走水完美版",
    statusId: "ok",
    images: [],
  },
  {
    id: "z6",
    name: "2026春 凍頂永隆B 青心烏龍 種 球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 650, "80": 1655, "150": 2785 },
    note: "走水稍卡版",
    statusId: "ok",
    images: [],
  },
  {
    id: "z7",
    name: "2025冬 竹山大沼澤 金萱 種 走乾球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 700, "80": 1555, "150": 2760 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z8",
    name: "2025冬 竹山大沼澤 金萱 種 中火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 725, "80": 1605, "150": 2850 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z9",
    name: "2025冬 竹山大沼澤 金萱 種 重火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 750, "80": 1660, "150": 2940 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z10",
    name: "2025冬 帖比倫瀑布 青心烏龍 種 走乾球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 780, "80": 1725, "150": 3060 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z11",
    name: "2025冬 帖比倫瀑布 青心烏龍 種 中火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 800, "80": 1775, "150": 3150 },
    note: null,
    statusId: "ok",
    images: [],
  },
  {
    id: "z12",
    name: "2025冬 帖比倫瀑布 青心烏龍 種 重火球形包種茶",
    region: "走水と炭焙",
    prices: { "30": 825, "80": 1825, "150": 3240 },
    note: null,
    statusId: "ok",
    images: [],
  },
];

export const PRODUCT_STATUSES: ProductStatus[] = [
  {
    id: "ok",
    label: "正常上架",
    type: "purchasable",
    color: null,
  },
  {
    id: "soldout",
    label: "已售完 Sold Out",
    type: "tag",
    color: "#d97b63",
  },
  {
    id: "comingsoon",
    label: "棋願製造中",
    type: "tag",
    color: "#c9bfa8",
  },
];

export const CUSTOMER_FIELDS: CustomerField[] = [
  {
    id: "name",
    label: "姓名",
    type: "text",
    required: true,
    builtin: true,
  },
  {
    id: "phone",
    label: "電話",
    type: "tel",
    required: true,
    builtin: true,
  },
  {
    id: "lineId",
    label: "LINE ID（滿 3,000 元可加入會員專屬群組）",
    type: "text",
    required: true,
    builtin: true,
  },
  {
    id: "email",
    label: "電子郵件",
    type: "email",
    required: true,
    builtin: true,
  },
  {
    id: "zip",
    label: "郵遞區號",
    type: "text",
    required: false,
    builtin: true,
  },
  {
    id: "address",
    label: "地址",
    type: "text",
    required: true,
    builtin: true,
  },
];

// 只保留 productIds 非空的組合折扣（原資料中還有一個空白模板組合，永遠不會符合條件，故排除）
export const BUNDLE_DISCOUNTS: BundleDiscount[] = [
  {
    name: "組合折扣",
    productIds: ["n14", "n15"],
    discountType: "percent",
    discountValue: 10,
  },
];

export const LOGO_IMAGE = "/images/logo.png";
export const LINE_PAY_QR_IMAGE = "/images/line-pay-qr.png";

export const WEIGHT_OPTIONS = [30, 80, 150] as const;
export const FREE_SHIPPING_THRESHOLD = 3000;
export const SHIPPING_FEE = 100;
